In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./thoracic_surgery.csv')
Data_set = df.values
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [3]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(Data_set, test_size=0.2)

X_train = train[:,0:17]
Y_train = train[:,17]
X_train

array([[137.  ,   2.  ,   3.76, ...,   1.  ,   0.  ,  54.  ],
       [ 38.  ,   3.  ,   3.68, ...,   0.  ,   0.  ,  61.  ],
       [ 80.  ,   3.  ,   3.04, ...,   0.  ,   0.  ,  78.  ],
       ...,
       [241.  ,   3.  ,   4.36, ...,   1.  ,   0.  ,  72.  ],
       [147.  ,   3.  ,   3.92, ...,   0.  ,   0.  ,  70.  ],
       [459.  ,   3.  ,   3.6 , ...,   0.  ,   0.  ,  46.  ]])

In [4]:
Y_train

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 0.

In [5]:
X_test = test[:, 0:17]
Y_test = test[:, 17]
X_test

array([[ 60.  ,   3.  ,   3.84, ...,   1.  ,   0.  ,  58.  ],
       [190.  ,   4.  ,   4.92, ...,   1.  ,   0.  ,  60.  ],
       [128.  ,   3.  ,   2.  , ...,   1.  ,   0.  ,  73.  ],
       ...,
       [ 31.  ,   3.  ,   3.24, ...,   1.  ,   0.  ,  55.  ],
       [415.  ,   3.  ,   1.46, ...,   1.  ,   0.  ,  68.  ],
       [371.  ,   3.  ,   2.88, ...,   1.  ,   0.  ,  59.  ]])

In [6]:
Y_test

array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0.])

In [7]:
from keras.models import Sequential
from keras.layers import Dense

In [8]:
model = Sequential()
model.add(Dense(30, input_dim=17, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [10]:
model.fit(X_train, Y_train, epochs=30, batch_size=10)

Epoch 1/30
38/38 [==============================] - 0s 642us/step - loss: 0.4856 - accuracy: 0.4854
Epoch 2/30
38/38 [==============================] - 0s 735us/step - loss: 0.1457 - accuracy: 0.8542
Epoch 3/30
38/38 [==============================] - 0s 671us/step - loss: 0.1167 - accuracy: 0.8832
Epoch 4/30
38/38 [==============================] - 0s 819us/step - loss: 0.1594 - accuracy: 0.8405
Epoch 5/30
38/38 [==============================] - 0s 690us/step - loss: 0.1534 - accuracy: 0.8465
Epoch 6/30
38/38 [==============================] - 0s 854us/step - loss: 0.1854 - accuracy: 0.8145
Epoch 7/30
38/38 [==============================] - 0s 928us/step - loss: 0.1447 - accuracy: 0.8552
Epoch 8/30
38/38 [==============================] - 0s 702us/step - loss: 0.1293 - accuracy: 0.8704
Epoch 9/30
38/38 [==============================] - 0s 970us/step - loss: 0.1370 - accuracy: 0.8603
Epoch 10/30
38/38 [==============================] - 0s 718us/step - loss: 0.1639 - accuracy: 0.8322

In [11]:
model.evaluate(X_test, Y_test)

3/3 [==============================] - 0s 917us/step - loss: 0.1489 - accuracy: 0.8511


[0.14888159930706024, 0.8510638475418091]

In [15]:
prediction = model.predict_classes(X_test)
prediction.ravel()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
import pandas as pd

In [17]:
comparison = pd.DataFrame({'prediction':prediction.ravel(), 'ground_truth':Y_test.astype(int)})
comparison

prediction  ground_truth
0            0             0
1            0             0
2            0             1
3            0             0
4            0             0
..         ...           ...
89           0             0
90           0             1
91           0             1
92           0             0
93           0             0

[94 rows x 2 columns]